### ISSUE TITLE
Compilation errors E0046, E0438

### ISSUE THREAD

**Issue by AmarenaCherry** [WarpspeedSCP/yet-cc-rs#1]
I've tried compiling the tools on your page and I've encountered errors, mainly pertaining to the SizedOpcode macro. I'm not very knowledgeable with Rust so I don't have much of an idea in how to debug this. Tried on both Windows and WSL.
[ERROR_E0046_E0438.txt](https://github.com/user-attachments/files/17966439/ERROR_E0046_E0438.txt)

**Comment by WarpspeedSCP** [comment]
I'm giving it a look now.

**Comment by WarpspeedSCP** [comment]
I've fixed this; just pull the latest commit. I've also updated the readme with some example script modifications for things like tips.
